-- V92: Seed de datos

INSERT INTO especialidad (id, nombre, descripcion) VALUES
  (1, 'Barro negro', 'Alfarería tradicional de San Bartolo Coyotepec'),
  (2, 'Alebrijes', 'Tallado y pintura de figuras fantásticas en copal'),
  (3, 'Textiles en telar de cintura', 'Tejido tradicional en algodón y lana'),
  (4, 'Talabartería', 'Trabajo artesanal en piel y cuero'),
  (5, 'Tallado en madera', 'Esculturas y utensilios en madera'),
  (6, 'Joyería en filigrana', 'Orfebrería fina en oro y plata'),
  (7, 'Cerámica de barro rojo', 'Alfarería vidriada tradicional'),
  (8, 'Cestería', 'Tejido de canastas en carrizo y palma'),
  (9, 'Bordado tradicional', 'Bordado a mano en prendas típicas'),
  (10, 'Hojalatería', 'Trabajo decorativo en lámina de metal'),
  (11, 'Velas artesanales', 'Elaboración de velas de cera labradas'),
  (12, 'Tapetes de lana', 'Tejido de tapetes en telar de pedal'),
  (13, 'Papel picado', 'Recorte artesanal de papel de china'),
  (14, 'Máscaras ceremoniales', 'Tallado de máscaras para danzas tradicionales'),
  (15, 'Vidrio soplado', 'Elaboración de piezas en vidrio fundido');

INSERT INTO comunidad (id, nombre, region, latitud, longitud) VALUES
  (1, 'San Bartolo Coyotepec', 'Valles Centrales', 16.925, -96.712),
  (2, 'San Martín Tilcajete', 'Valles Centrales', 16.855, -96.674),
  (3, 'Teotitlán del Valle', 'Valles Centrales', 17.032, -96.527),
  (4, 'Santa María Atzompa', 'Valles Centrales', 17.093, -96.759),
  (5, 'San Antonino Castillo Velasco', 'Valles Centrales', 16.783, -96.68),
  (6, 'Villa de Etla', 'Valles Centrales', 17.198, -96.799),
  (7, 'Ocotlán de Morelos', 'Valles Centrales', 16.796, -96.676),
  (8, 'San Pedro Cajonos', 'Sierra Norte', 17.259, -96.29),
  (9, 'Santo Tomás Jalieza', 'Valles Centrales', 16.82, -96.68),
  (10, 'Tlacolula de Matamoros', 'Valles Centrales', 16.958, -96.478),
  (11, 'Juchitán de Zaragoza', 'Istmo', 16.436, -95.019),
  (12, 'Santa Ana del Valle', 'Valles Centrales', 16.997, -96.48),
  (13, 'San Agustín de las Juntas', 'Valles Centrales', 17.006, -96.72),
  (14, 'Mitla', 'Valles Centrales', 16.921, -96.359),
  (15, 'Huajuapan de León', 'Mixteca', 17.807, -97.777);

INSERT INTO usuario (id, nombre, correo, password_hash, activo, rol_id) VALUES
  (100, 'Doroteo Ramírez Mendoza', 'doroteo.ramirez@aripo.gob.mx', '$2a$10$kGdwbSlaY0cDvTApmkp/HeZbjhxKyLpzMEyA1OlqC6wfUQbPfQOMq', 1, 2),
  (101, 'Alfonsina López Martínez', 'alfonsina.lopez@aripo.gob.mx', '$2a$10$kGdwbSlaY0cDvTApmkp/HeZbjhxKyLpzMEyA1OlqC6wfUQbPfQOMq', 1, 2),
  (102, 'Isidoro Cruz Hernández', 'isidoro.cruz@aripo.gob.mx', '$2a$10$kGdwbSlaY0cDvTApmkp/HeZbjhxKyLpzMEyA1OlqC6wfUQbPfQOMq', 1, 2),
  (103, 'Petra Santiago García', 'petra.santiago@aripo.gob.mx', '$2a$10$kGdwbSlaY0cDvTApmkp/HeZbjhxKyLpzMEyA1OlqC6wfUQbPfQOMq', 1, 2),
  (104, 'Melquiades Vásquez Ruiz', 'melquiades.vasquez@aripo.gob.mx', '$2a$10$kGdwbSlaY0cDvTApmkp/HeZbjhxKyLpzMEyA1OlqC6wfUQbPfQOMq', 1, 2),
  (105, 'Guadalupe Morales Jiménez', 'guadalupe.morales@aripo.gob.mx', '$2a$10$kGdwbSlaY0cDvTApmkp/HeZbjhxKyLpzMEyA1OlqC6wfUQbPfQOMq', 1, 2),
  (106, 'Nicolás Bautista Pérez', 'nicolas.bautista@aripo.gob.mx', '$2a$10$kGdwbSlaY0cDvTApmkp/HeZbjhxKyLpzMEyA1OlqC6wfUQbPfQOMq', 1, 2),
  (107, 'Remedios Ortega Luna', 'remedios.ortega@aripo.gob.mx', '$2a$10$kGdwbSlaY0cDvTApmkp/HeZbjhxKyLpzMEyA1OlqC6wfUQbPfQOMq', 1, 2),
  (108, 'Eleuterio Gómez Ramos', 'eleuterio.gomez@aripo.gob.mx', '$2a$10$kGdwbSlaY0cDvTApmkp/HeZbjhxKyLpzMEyA1OlqC6wfUQbPfQOMq', 1, 2),
  (109, 'Casimira Flores Antonio', 'casimira.flores@aripo.gob.mx', '$2a$10$kGdwbSlaY0cDvTApmkp/HeZbjhxKyLpzMEyA1OlqC6wfUQbPfQOMq', 1, 2),
  (110, 'Teodoro Aguilar Mendez', 'teodoro.aguilar@aripo.gob.mx', '$2a$10$kGdwbSlaY0cDvTApmkp/HeZbjhxKyLpzMEyA1OlqC6wfUQbPfQOMq', 1, 2),
  (111, 'Filomena Reyes Castellanos', 'filomena.reyes@aripo.gob.mx', '$2a$10$kGdwbSlaY0cDvTApmkp/HeZbjhxKyLpzMEyA1OlqC6wfUQbPfQOMq', 1, 2),
  (112, 'Anselmo Juárez Velasco', 'anselmo.juarez@aripo.gob.mx', '$2a$10$kGdwbSlaY0cDvTApmkp/HeZbjhxKyLpzMEyA1OlqC6wfUQbPfQOMq', 1, 2),
  (113, 'Eustaquia Cortés Ramírez', 'eustaquia.cortes@aripo.gob.mx', '$2a$10$kGdwbSlaY0cDvTApmkp/HeZbjhxKyLpzMEyA1OlqC6wfUQbPfQOMq', 1, 2),
  (114, 'Bonifacio Méndez Sánchez', 'bonifacio.mendez@aripo.gob.mx', '$2a$10$kGdwbSlaY0cDvTApmkp/HeZbjhxKyLpzMEyA1OlqC6wfUQbPfQOMq', 1, 2);

INSERT INTO artesano (id, usuario_id, comunidad_id, curp, biografia, anios_oficio, lengua, estado_validacion) VALUES
  (1, 100, 1, 'UDAX770408HOCRSNED', 'Artesano con amplia trayectoria en su oficio, originario de San Bartolo Coyotepec.', 39, 'Zapoteco', 'APROBADO'),
  (2, 101, 2, 'CSNB610207MOCMRLH6', 'Artesano con amplia trayectoria en su oficio, originario de San Martín Tilcajete.', 6, 'Mixteco', 'APROBADO'),
  (3, 102, 3, 'RGWU940708HOCLPZ48', 'Artesano con amplia trayectoria en su oficio, originario de Teotitlán del Valle.', 22, 'Español', 'APROBADO'),
  (4, 103, 4, 'ZAYZ701214MOCGRC0I', 'Artesano con amplia trayectoria en su oficio, originario de Santa María Atzompa.', 14, 'Zapoteco', 'EN_REVISION'),
  (5, 104, 5, 'GYKD650704HOCVLZ11', 'Artesano con amplia trayectoria en su oficio, originario de San Antonino Castillo Velasco.', 21, 'Español', 'APROBADO'),
  (6, 105, 6, 'ZBXO940213MOCHRNC7', 'Artesano con amplia trayectoria en su oficio, originario de Villa de Etla.', 23, 'Mixe', 'APROBADO'),
  (7, 106, 7, 'UTLS721203HOCSNTBH', 'Artesano con amplia trayectoria en su oficio, originario de Ocotlán de Morelos.', 23, 'Zapoteco', 'EN_REVISION'),
  (8, 107, 8, 'CHDM770821MOCRML1F', 'Artesano con amplia trayectoria en su oficio, originario de San Pedro Cajonos.', 28, 'Español', 'APROBADO'),
  (9, 108, 9, 'LGVI641021HOCJMNF7', 'Artesano con amplia trayectoria en su oficio, originario de Santo Tomás Jalieza.', 20, 'Chinanteco', 'APROBADO'),
  (10, 109, 10, 'FOMI950422MOCPRZ0B', 'Artesano con amplia trayectoria en su oficio, originario de Tlacolula de Matamoros.', 19, 'Zapoteco', 'RECHAZADO'),
  (11, 110, 11, 'BZKM770207HOCLNA80', 'Artesano con amplia trayectoria en su oficio, originario de Juchitán de Zaragoza.', 18, 'Español', 'APROBADO'),
  (12, 111, 12, 'UPMU890309MOCRMSEH', 'Artesano con amplia trayectoria en su oficio, originario de Santa Ana del Valle.', 40, 'Mixteco', 'APROBADO'),
  (13, 112, 13, 'RIXS871013HOCNTN1H', 'Artesano con amplia trayectoria en su oficio, originario de San Agustín de las Juntas.', 13, 'Zapoteco', 'EN_REVISION'),
  (14, 113, 14, 'QPCY630205MOCMNDF3', 'Artesano con amplia trayectoria en su oficio, originario de Mitla.', 9, 'Español', 'APROBADO'),
  (15, 114, 15, 'MMTO930518HOCVSQAD', 'Artesano con amplia trayectoria en su oficio, originario de Huajuapan de León.', 39, 'Mixteco', 'APROBADO');

INSERT INTO artesano_especialidad (artesano_id, especialidad_id) VALUES
  (1, 13),
  (1, 11),
  (2, 2),
  (2, 5),
  (3, 3),
  (3, 8),
  (4, 12),
  (5, 5),
  (5, 9),
  (5, 13),
  (6, 9),
  (7, 14),
  (8, 5),
  (8, 14),
  (8, 11),
  (9, 10),
  (9, 4),
  (9, 3),
  (10, 13),
  (10, 3),
  (11, 13),
  (11, 9),
  (11, 1),
  (12, 6),
  (12, 8),
  (12, 1),
  (13, 15),
  (14, 15),
  (14, 14),
  (15, 4),
  (15, 1);

INSERT INTO taller (id, nombre, descripcion, direccion, municipio, comunidad_id) VALUES
  (1, 'Taller Alfarería Coyotepec', 'Taller dedicado a barro negro.', 'Calle Principal #31, San Bartolo Coyotepec', 'San Bartolo Coyotepec', 1),
  (2, 'Alebrijes del Valle', 'Taller dedicado a alebrijes.', 'Calle Principal #113, San Martín Tilcajete', 'San Martín Tilcajete', 2),
  (3, 'Telares Zapotecos', 'Taller dedicado a textiles en telar de cintura.', 'Calle Principal #73, Teotitlán del Valle', 'Teotitlán del Valle', 3),
  (4, 'Barro y Tierra Atzompa', 'Taller dedicado a talabartería.', 'Calle Principal #11, Santa María Atzompa', 'Santa María Atzompa', 4),
  (5, 'Bordados San Antonino', 'Taller dedicado a tallado en madera.', 'Calle Principal #11, San Antonino Castillo Velasco', 'San Antonino Castillo Velasco', 5),
  (6, 'Cuero y Arte Etla', 'Taller dedicado a joyería en filigrana.', 'Calle Principal #94, Villa de Etla', 'Villa de Etla', 6),
  (7, 'Cerámica Ocotlán', 'Taller dedicado a cerámica de barro rojo.', 'Calle Principal #63, Ocotlán de Morelos', 'Ocotlán de Morelos', 7),
  (8, 'Cestería Sierra Norte', 'Taller dedicado a cestería.', 'Calle Principal #105, San Pedro Cajonos', 'San Pedro Cajonos', 8),
  (9, 'Hilos de Jalieza', 'Taller dedicado a bordado tradicional.', 'Calle Principal #9, Santo Tomás Jalieza', 'Santo Tomás Jalieza', 9),
  (10, 'Hojalata Tlacolula', 'Taller dedicado a hojalatería.', 'Calle Principal #98, Tlacolula de Matamoros', 'Tlacolula de Matamoros', 10),
  (11, 'Velas del Istmo', 'Taller dedicado a velas artesanales.', 'Calle Principal #69, Juchitán de Zaragoza', 'Juchitán de Zaragoza', 11),
  (12, 'Tapetes Santa Ana', 'Taller dedicado a tapetes de lana.', 'Calle Principal #99, Santa Ana del Valle', 'Santa Ana del Valle', 12),
  (13, 'Papel y Color', 'Taller dedicado a papel picado.', 'Calle Principal #17, San Agustín de las Juntas', 'San Agustín de las Juntas', 13),
  (14, 'Máscaras de Mitla', 'Taller dedicado a máscaras ceremoniales.', 'Calle Principal #17, San Pablo Villa de Mitla', 'San Pablo Villa de Mitla', 14),
  (15, 'Vidrio Huajuapan', 'Taller dedicado a vidrio soplado.', 'Calle Principal #85, Huajuapan de León', 'Huajuapan de León', 15);

INSERT INTO artesano_taller (taller_id, artesano_id) VALUES
  (9, 1),
  (3, 1),
  (9, 2),
  (14, 2),
  (4, 3),
  (9, 3),
  (12, 4),
  (7, 5),
  (11, 5),
  (8, 6),
  (9, 6),
  (2, 7),
  (4, 7),
  (2, 8),
  (1, 9),
  (10, 9),
  (10, 10),
  (1, 11),
  (12, 12),
  (4, 13),
  (15, 14),
  (14, 15);

INSERT INTO artesania (id, nombre, descripcion, precio, existencia, imagen_url, taller_id) VALUES
  (1, 'Olla de barro negro', 'Olla decorativa bruñida a mano', 450.0, 12, NULL, 1),
  (2, 'Alebrije jaguar', 'Figura de copal tallada y pintada', 1200.0, 5, NULL, 2),
  (3, 'Rebozo de algodón', 'Tejido en telar de cintura', 850.0, 8, NULL, 3),
  (4, 'Cazuela de barro rojo', 'Cazuela vidriada para cocina', 320.0, 20, NULL, 4),
  (5, 'Blusa bordada', 'Bordado floral a mano', 680.0, 10, NULL, 5),
  (6, 'Cinturón de piel', 'Talabartería repujada', 540.0, 15, NULL, 6),
  (7, 'Juego de tazas', 'Cerámica esmaltada', 380.0, 18, NULL, 7),
  (8, 'Canasta de carrizo', 'Cestería tejida a mano', 220.0, 25, NULL, 8),
  (9, 'Servilleta bordada', 'Bordado tradicional de Jalieza', 180.0, 30, NULL, 9),
  (10, 'Farol de hojalata', 'Lámpara decorativa perforada', 410.0, 9, NULL, 10),
  (11, 'Vela labrada', 'Cera de abeja decorada', 150.0, 40, NULL, 11),
  (12, 'Tapete de lana', 'Tejido en telar de pedal con tintes naturales', 2400.0, 4, NULL, 12),
  (13, 'Guirnalda de papel picado', 'Papel de china recortado', 90.0, 50, NULL, 13),
  (14, 'Máscara de danzante', 'Máscara tallada en madera', 780.0, 6, NULL, 14),
  (15, 'Jarrón de vidrio soplado', 'Pieza de vidrio reciclado', 560.0, 11, NULL, 15);